---
language: node_js
node_js:
  - 13.7
  - 12.0
cache:
  directories:
  - node_modules
  - vendor
before_script:
  - gem install bundler
  - npm install -g gulp yarn
script:
  - gulp build
install:
  - npm install
