# the base hostname & protocol for your site, e.g. http://example.com
url: "https://williamcanin.me"
# the subpath of your site, e.g. /blog
baseurl: ""





# Attention! Do not change the information below as it is 
# for development unless you know what you are doing.

plugins:
  - jemoji
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-jsminify
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-coffeescript

include: ['_blog','_pages']

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

permalink: /blog/:title/

layouts_dir: _src/_layouts
includes_dir: _src/_includes
plugins_dir: _src/_plugins

destination: public
port: 4000
host: localhost

sass:
  load_paths:
  - _src/_sass
  - vendor/node_modules
  style: compressed

feed:
  path: feed.xml

compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

tag_page_layout: tag
tag_page_dir: blog/tags
tag_permalink_style: pretty

imager:
  dir_posts: "assets/images/posts"

reading_time:
  locale: en_US

datelang:
  locale: en_US
  reload: true

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  sort_field: 'date'
  sort_reverse: true
  per_page: 5
  permalink: '/:num/'
  locale: ''
  title: ':title - Page :num'
  limit: 0
  # extension: html
  indexpage: 'index'

gist:
  noscript: false

exclude:
  - temp
  - .hidden
  - node_modules
  - _src
  - vendor
  - Gemfile
  - Gemfile.lock
  - screenshot.png
  - CHANGELOG
  - COPYING
  - package-lock.json
  - package.json
  - README.md
  - Rakefile
  - yarn.lock
  - Makefile
